#
# This file differs from the original that can be found in https://github.com/smartmicro/smartmicro_ros2_radars
#


/smart_radar:
  ros__parameters:
    adapters:
      adapter_0:
        hw_dev_id: 3
        hw_iface_name: eth0
        hw_type: eth
        port: 55555
    master_data_serial_type: port_based
    master_inst_serial_type: port_based
    sensors:
      # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
      # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
      # 
      # Sensor `model` names if using link type:
      # can: 'umrra4_can_mse_v1_0_0', 'umrr9f_can_mse_v1_1_0', 'umrr9f_can_mse_v1_0_0', 'umrr96_can_v1_2_2', 'umrr11_can_v1_1_2', 'umrr9f_can_v2_1_1', 'umrr9f_can_v2_2_1',
      #      'umrr9f_can_v2_4_1'. 'umrr9d_can_v1_0_3', 'umrr9d_can_v1_2_2', 'umrr9d_can_v1_4_1', 'umrr9d_can_v1_5_0', 'umrra4_can_v1_0_1', 'umrra4_can_v1_2_1', 'umrra4_can_v1_4_0'
      #
      # port: 'umrra4_mse_v1_0_0', 'umrr9f_mse_v1_1_0', 'umrr9f_mse_v1_0_0', 'umrr96_v1_2_2', 'umrr11_v1_1_2', 'umrr9f_v2_1_1', 'umrr9f_v2_2_1', 'umrr9f_v2_4_1'. 'umrr9d_v1_0_3',
      #       'umrr9d_v1_2_2', 'umrr9d_v1_4_1', 'umrr9d_v1_5_0', 'umrra4_v1_0_1', 'umrra4_v1_2_1', 'umrra4_v1_4_0'
      sensor_0:
        # The link of the sensor either 'can' or 'eth'
        link_type: "eth"
        # The publisher type of the sensor
        pub_type: "target"
        # The model of the connected sensor.
        # model: "umrr11_v1_1_2"
        model: "umrra4_v1_2_1"
        # Adapter id to which sensor is connected
        dev_id: 3
        # The client_id of the sensor/source, must be a unique integer.
        id: 100
        # The ip address of the sensor or of the source acting as a sensor.
        ip: "192.168.11.11"
        # The port to be used.
        port: 55555
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
        inst_type: "port_based"
        data_type: "port_based"
        # The interface name of the sensor
        # uifname: "umrr11_t132_automotive"
        uifname: "umrra4_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 2
        # The pathc version of the interface
        uifpatchv: 1
      # sensor_0:
      #   # The link of the sensor either 'can' or 'eth'
      #   link_type: "eth"
      #   # The publisher type of the sensor
      #   pub_type: "mse"
      #   # The model of the connected sensor.
      #   # model: "umrra4_mse_v1_0_0"
      #   model: "umrra4_mse_v1_2_1"
      #   # Adapter id to which sensor is connected
      #   dev_id: 3
      #   # The client_id of the sensor/source, must be a unique integer.
      #   id: 100
      #   # The ip address of the sensor or of the source acting as a sensor.
      #   # ip: "172.22.10.101"
      #   # ip: "192.168.11.17"
      #   ip: "192.168.11.11"
      #   # The port to be used.
      #   port: 55555
      #   # The frame_id to be set to the published messages.
      #   frame_id: "umrr"
      #   # Specify the history size.
      #   history_size: 10
      #   inst_type: "port_based"
      #   data_type: "port_based"
      #   # The interface name of the sensor
      #   # uifname: "umrr11_t132_automotive"
      #   uifname: "umrra4_mse"
      #   # The major version of the interface
      #   uifmajorv: 1
      #   # The minor version of the interface
      #   uifminorv: 0
      #   # The pathc version of the interface
      #   uifpatchv: 0
